# Generated by Django 4.2.3 on 2024-01-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='mount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='pledge',
            old_name='omment',
            new_name='comment',
        ),
    ]
